name: flutter_sqflite_practice
description: A project for flutter sqflite practice.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  provider: ^4.3.3
  sqflite: ^1.3.2+3
  path_provider: ^1.6.27
  keyboard_actions: ^3.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
